export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const ERR_MSG = 'ERR_MSG'
export const USER_INFO = 'USER_INFO'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'